### ISSUE TITLE
Have you compared your model with the Transformer with caching strategy?

### ISSUE THREAD

**Issue by chqiwang** [bzhangXMU/transformer-aan#1]

**Comment by bzhangGo** [comment]
Hi @chqiwang,

We have conducted some experiments to examine the acceleration of AAN on Transformer against its cached implementation (as in the new THUMT). We used the AAN without FFN activation. Under this setting, our AAN can be trained faster and achieves similar translation performance. The decoding can be accelerated by 20%~26% on NIST Chinese-English translation tasks. Considering language differences, we believe that in general, AAN can accelerate the decoding by 25%~45% for different langauge pairs.

Very recently, [Marian](https://arxiv.org/pdf/1805.12096.pdf) uses our AAN model for  the WNMT 2018 shared task. With excellent engineering, Transformer with AAN can achieve an acceleration of ~2. 
![image](https://user-images.githubusercontent.com/17406686/41138220-5a1d882a-6b12-11e8-9405-7ecde38a90a7.png)
