### ISSUE TITLE
Questions about the data

### ISSUE THREAD

**Issue by lucas-acc** [bzhangXMU/transformer-aan#2]
Thank you for your excellent work!

I have understood the architecture of AAN and most of the designs of this implementation, and I run it with Transformer-AAN-Data  successfully. Now I have some questions about the data.

In the data directory, there are following files:
`dev.32k.de  dev.en.plain           newstest2014.32k.en  train.32k.de.shuf  vocab.32k.en.txt
dev.32k.en  multi-bleu-detok.perl  newstest2014.de      train.32k.en.shuf  vocab.de
dev.de      multi-bleu.perl        newstest2014.en      vocab.32k.de.txt   vocab.en`

The file used are:
`dev.32k.de   train.32k.de.shuf  vocab.32k.en.txt
dev.32k.en   train.32k.en.shuf   vocab.32k.de.txt`

My questions are:
1.What's the uses of unused files?
2.How to shuffle parallel corpora to get train.32k.de.shuf and train.32k.en.shuf?

**Comment by bzhangGo** [comment]
Hi @NLPpupil ,

1. What's the use of unused files?
a. The used files you pointed out are _only for training purpose_, and most of the others are for testing purpose, which is an essential phase for reporting your final BLEU scores. 
b. During testing, you need `dev.32k.en` and `newstest2014.32k.en` as your source input files, and evaluate your model with gold reference file `dev.de` and `newstest2014.de` respectively. 
c. Personally, I also provide some evaluation scripts, including `multi-bleu.perl` and `multi-bleu-detok.perl`. The former is used to evaluate tokenized BLEU score, while the latter is for de-tokenized BLEU score. 
In our paper, we used the former for the WMT14 translation tasks, while the latter for the WMT17 translation tasks.
d. In terms of other files, these are unnecessary. When I uploadding the dataset, I simply put all files into the folder without any cleaning. You can safely remove them without any risk.

2. How to shuffle parallel corpora to get train.32k.de.shuf and train.32k.en.shuf?
THUMT provides the script to do this, [shuffle_corpus.py](https://github.com/bzhangXMU/transformer-aan/blob/master/code/thumt/scripts/shuffle_corpus.py). If you are interested the detailed pre-processing procedure, I refer you to the mannual given in the [THUMT Mannual](https://github.com/thumt/THUMT/blob/master/UserManual.pdf).

**Comment by lucas-acc** [comment]
你完美解决了我的困惑，谢谢！
