### ISSUE TITLE
Will you implement cache?

### ISSUE THREAD

**Issue by lucas-acc** [bzhangXMU/transformer-aan#5]
Will you implement cache? 
How much faster if combine cache with ANN in theory?
How much code do I need to modify if I have to do it myself?

**Comment by bzhangGo** [comment]
Hi @NLPpupil,

The original Transformer needs a cache to try to avoid repeatedly computing the attention weights over all previous hidden states (from 1 to t-1). Generally, the cache saves the pre-calculated projections before generating the attention weights. However, our AAN requires no dynamic attentions, it only needs the last previous hidden states (t-1). In this respect, the given code has already implemented the cache, although it can be further optimized with better engineering.
