### ISSUE TITLE
Questions about  discussion: "Why AAN can accelerate the Transformer with a factor of 4~7?"

### ISSUE THREAD

**Issue by xiangrongzeng** [bzhangXMU/transformer-aan#6]
For the original Transformer decoder,  in one step, you give the computational complexity of self-attention as O([n_tgt d^2]). Is it the same as O(n_tgt * d^2)? 

If not, what is O([n_tgt d^2]) means? 
If yes, I think the computational complexity of self-attention should be O(n_tgt^2 * d), the computational complexity of cross-attention should be O(n_tgt * n_src * d) and the computational complexity of FFN is O(n_tgt * d^2). Therefor, is we denote n_tgt and n_src both as n, the total complexity is O(n^2 * d + n * d^2), which is the same as the results in Table 1 ("Attention is all you need") and Table 1 (your paper).

**Comment by bzhangGo** [comment]
Hi @xiangrongzeng,

In the discussion, O([n_tgt d^2]) is exactly the same as O(n_tgt * d^2). 

One thing you should notice is that this complexity is not for the whole decoder part, it's only for **one step**. This means we only consider *one target token*, so it's O(n_tgt * d^2) rather than O(n_tgt^2 * d^2).

**Comment by xiangrongzeng** [comment]
Thankyou for your reply.

It's my fault that didn't notice the "one step" setting. However, I'm still confused. Why the complexity of self-attention in one step is O(n_tgt * d^2)? I still think this should be O(n_tgt * d). Therefor the complexity of  n_tgt steps of self-attention is O(n_tgt^2 * d), which is the same with Table 1 in "Attention is all you need".

**Comment by bzhangGo** [comment]
In "Attention is all you need", they state that the complexity of self-attention is O(n^2 * d), just as shown in Eq. (1).

However, there are two parts in one self-attention layer: one is for mapping inputs to query, key and memories, whose complexity is O(n * d^2); the another one is for self-attention (Eq. (1)), whose complexity is O(n^2 * d) . Therefore, I'm not sure whether we can only including O(n^2 * d) as the complexity of the whole layer.
